import {
  Atom,
  Layers,
  FileCode2,
  Blocks,
  Paintbrush,
  Braces,
  Leaf,
  Server,
  Cpu,
  Sparkles,
  Database,
  GitBranch,
  Cloud,
  Figma,
  FlaskConical,
  LayoutPanelLeft,
  Wrench,
  Rocket,
  Briefcase,
  Code2,
  Flag,
  MapPin,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  atom: Atom,
  layers: Layers,
  filecode: FileCode2,
  blocks: Blocks,
  paintbrush: Paintbrush,
  braces: Braces,
  leaf: Leaf,
  server: Server,
  cpu: Cpu,
  sparkles: Sparkles,
  database: Database,
  gitbranch: GitBranch,
  cloud: Cloud,
  figma: Figma,
  flask: FlaskConical,
  layout: LayoutPanelLeft,
  wrench: Wrench,
  rocket: Rocket,
  briefcase: Briefcase,
  code: Code2,
  sparkles2: Sparkles,
  flag: Flag,
  mappin: MapPin,
};
